<?xml version="1.0" encoding="utf-8"?><Database Name="WORKER" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-GHA5269\SQLEXPRESS;Initial Catalog=WORKER;Integrated Security=True" SettingsObjectName="ReportToPDF.Properties.Settings" SettingsPropertyName="WORKERConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Worker" Member="Workers">
    <Type Name="Worker">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="passwod" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>